name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: Lint tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup go 1.16
        uses: actions/setup-go@v3
        with:
          go-version: 1.16
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Run lint tests
        run: |
          mkdir bin
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.46.2
          export PATH=./bin:$PATH
          make lint
